[build]
builder = "go"
buildCommand = "apt-get update && apt-get install -y gcc && CGO_ENABLED=1 go build -o out cmd/server/main.go"

[deploy]
startCommand = "./main"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
GO_ENV = "production"